# -*- coding: utf-8 -*-
"""Excel_join_on_column.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CklG4JkfW9P069XB1ExgiCg3-_8QHLwJ
"""

import os
import pandas as pd

data_location = "ExcelData/FileLocation"
desired_headings = ["Valuable Information"]
df_total = pd.DataFrame(columns=desired_headings)

for file in os.listdir(data_location):
    df_file = pd.read_excel(data_location + file)
    selected_columns = df_file.loc[:, desired_headings]
    df_total = pd.concat([selected_columns, df_total], ignore_index=True)

df_total.to_excel("ValuableInformation.xlsx")